- name: Create users if not defined
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  roles:
    - student_users

- name: Create lab instances in AWS
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  vars:
    teardown: false
    create_lab: true
  roles:
    - manage_ec2_instances

- name: wait for all nodes to have SSH reachability
  hosts: "managed_nodes:control_nodes"
  become: yes
  gather_facts: no
  roles:
    - reachability

- name: Configure common options on managed nodes and control nodes
  hosts: "managed_nodes:control_nodes"
  become: yes
  roles:
    - user_accounts
    - common

- name: Configure control node
  hosts: control_nodes
  become: yes
  roles:
    - control_node

- name: Email inventory to students
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  roles:
    - email
