- block:
  - name: enable GigabitEthernet2 interface if compliant on r2
    net_interface:
      name: GigabitEthernet2
      description: interface to host1
      state: present

  - name: dhcp configuration for GigabitEthernet2
    ios_config:
      lines:
        - ip address dhcp
      parents: interface GigabitEthernet2
  when:
    - ansible_net_version == ios_version
    - '"rtr2" in inventory_hostname'
