---
- name: R1 gre configuration
  hosts: student1-rtr1.net-ws.redhatgov.io
  vars:
    ansible_network_os: ios
    ansible_connection: local
    rtr1_public_ip: "34.236.147.137"
    rtr2_public_ip: "54.209.50.0"
  gather_facts: no

  tasks:
    - name: create tunnel interface to R2
      ios_config:
        lines:
         - ip address 10.0.0.1 255.255.255.0
         - tunnel source GigabitEthernet1
         - tunnel destination {{rtr2_public_ip}}
        parents: interface Tunnel 0


- name: R2 gre configuration
  hosts: student1-rtr2.net-ws.redhatgov.io
  vars:
    ansible_network_os: ios
    ansible_connection: local
  gather_facts: no

  tasks:

    - name: create tunnel interface to R1
      ios_config:
        lines:
         - ip address 10.0.0.2 255.255.255.0
         - tunnel source GigabitEthernet1
         - tunnel destination {{rtr1_public_ip}}
        parents: interface Tunnel 0
