---
- name: Configure GRE Tunnel between rtr1 and rtr2
  hosts: all
  vars:
     ansible_network_os: ios
     ansible_connection: local
  gather_facts: no
  tasks:
  - name: teardown tunnel interface to R2
    ios_interface:
      name: interface tunnel 0
      state: absent
