# create users if not defined, using integer student_total
- name: Create Users
  template:
    src: student_list.j2
    dest: ./generated_student_list.txt
  register: student_list
  when: users == ""

# - name: debug generated_student_list
#   debug:
#     var: student_list

# now load the student into variables
- name: Include dynamically created generated_student_list.txt
  include_vars:
    file: generated_student_list.txt
  when: users == ""

# - name: debug users now
#   debug:
#     var: users
