- name: create student webpage
  template:
    src: ./templates/index.html.j2
    dest: "./{{ ec2_name_prefix|lower }}-index.html"

- name: create s3 bucket
  s3_bucket:
    name: "{{ec2_name_prefix|lower}}.{{workshop_dns_zone|lower}}"

- name: enable web hosting
  s3_website:
   name: "{{ec2_name_prefix|lower}}.{{workshop_dns_zone|lower}}"
   state: present
   region: "{{ec2_region}}"
   suffix: "{{ ec2_name_prefix|lower }}-index.html"
  register: s3_site

- name: DNS for student webpage
  route53:
    state: present
    zone: "{{workshop_dns_zone}}"
    record: "{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}"
    type: CNAME
    overwrite: yes
    value: "{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}.s3-website-{{ec2_region}}.amazonaws.com"

- name: PUT student webpage
  s3_sync:
    bucket: "{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}"
    region: "{{ec2_region}}"
    file_root: ./
    mime_map:
      .html: text/html
    permission: public-read
    include: "{{ ec2_name_prefix|lower }}-index.html"
